#cloud-config
rancher:
  environment:
    ETCD_DISCOVERY: https://discovery.etcd.io/c2c219023108cda9529364d6d983fe13
    FLANNEL_NETWORK: 10.244.0.0/16
  network:
    interfaces:
      eth*:
        dhcp: true
      "mac=52:54:00:12:34:59":
        address: 10.10.2.17/24
        gateway: 10.10.2.2
        mtu: 1500
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2Sx8dhcxM16zUIJGUsoHvium2ezzXL5F5obBvWd441BSau1XTDVdO3zOchF3mWvYX5q4JT1CF4GntvM1vc16acuVmkzsjsDe3+4uVPPzJps01vDxVeV1vRM53P2deCUnrFJ48CvrPisyXSOCtUCRFC1pPdvVAnOyTkzboQkCEbt6551bXF2nTnZu7XOSdzAKj+YLIRNf/ecr4hJi9xW7Q4N6gP0C+zn/KjvFQ0QSN5t8Cpbg4ri7uR2Vd4a0ccyJ5TQLRJ3EtAvuVZK3CeY0B3/XlD31cLMSFgLpWDBU2p9OC27Lc3grcYL2kN1A1HsV5AjBWRfTnFuCcOQ7MNdjJ root@ip-172-31-27-41

